using System;
using System.Collections.Generic;
using System.Linq;
using Airlift.Welcome;
using TMPro;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

// Owner 2026-09-17: "hone in on the edges of the entire card experience ... make it look much more polished from beginning
// to end". One card language on every screen: 4x MSAA at full render scale; high-resolution anti-aliased card, pill,
// stroke and shadow sprites (generated by scripts/make_card_sprites.py); pills that stay capsules at any height; the
// catalog art clipped to the card's top corners with a soft fade; a hairline stroke and a soft shadow on every card
// (consent, welcome, catalog, assistant bar, and the Cargo, Café and Garden lesson cards); lesson buttons as pills;
// the assistant caption kept inside the bar. Idempotent. Saves CargoCrew and the render pipeline assets.
// Run after the sprite generator: unity command run_script --file AgentScripts/PolishCards.cs --entry PolishCards.Run
public static class PolishCards
{
    const string ScenePath = "Assets/Airlift/Scenes/CargoCrew.unity", Sprites = "Assets/Airlift/Sprites/";
    const float PillBorderPx = 128f, ShadowPad = 24f, ShadowDrop = 10f;

    public static string Run()
    {
        for (int i = 0; i < SceneManager.sceneCount; i++)
            if (SceneManager.GetSceneAt(i).isDirty) throw new InvalidOperationException("Review dirty scenes first.");
        var report = new List<string>();

        // 1. Rendering: anti-aliased edges at full resolution on the Quest (Mobile) and desktop (PC) pipeline assets.
        foreach (var name in new[] { "Mobile_RPAsset", "PC_RPAsset" })
        {
            var asset = AssetDatabase.LoadAssetAtPath<ScriptableObject>("Assets/Settings/" + name + ".asset");
            var so = new SerializedObject(asset);
            so.FindProperty("m_MSAA").intValue = 4; so.FindProperty("m_RenderScale").floatValue = 1f;
            so.ApplyModifiedPropertiesWithoutUndo(); EditorUtility.SetDirty(asset);
        }
        report.Add("MSAA 4x, render scale 1.0");

        // 2. Sprite imports.
        var card = Import("NerdyCard", 400, new Vector4(112, 112, 112, 112));
        var pill = Import("NerdyPill", 100, new Vector4(PillBorderPx, PillBorderPx, PillBorderPx, PillBorderPx));
        var stroke = Import("NerdyStroke", 400, new Vector4(112, 112, 112, 112));
        var shadow = Import("NerdyShadow", 200, new Vector4(96, 96, 96, 96));
        var art = Import("NerdyCardArt", 400, Vector4.zero);
        var fade = Import("NerdyFade", 100, Vector4.zero);

        var scene = EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
        var n = UnityEngine.Object.FindAnyObjectByType<NerdyDirector>(FindObjectsInactive.Include);
        if (n == null) throw new InvalidOperationException("NerdyDirector missing.");
        var images = scene.GetRootGameObjects().SelectMany(g => g.GetComponentsInChildren<Image>(true)).ToList();

        // 3. Shapes: retire the low-resolution rounded rect; cards take the card shape, buttons and chips become pills.
        int swapped = 0, pills = 0;
        foreach (var image in images)
        {
            if (image.sprite == null) continue;
            var rect = image.rectTransform.rect;
            if (image.sprite.name == "RoundedRect") { image.sprite = Mathf.Min(rect.width, rect.height) >= 150f ? card : pill; image.type = Image.Type.Sliced; swapped++; }
            if (image.sprite == card) image.pixelsPerUnitMultiplier = 1f;
            if (image.sprite == pill)
            {
                // Border 128 px at 100 ppu is 128 canvas units; the multiplier makes it exactly half the pill's height.
                image.type = Image.Type.Sliced;
                image.pixelsPerUnitMultiplier = PillBorderPx / (Mathf.Max(1f, Mathf.Min(rect.width, rect.height)) / 2f);
                pills++;
            }
            EditorUtility.SetDirty(image);
        }
        report.Add(swapped + " rounded rects retired, " + pills + " capsule pills");

        // 3b. Gradient pills: stencil masks cannot anti-alias, so a masked brand-gradient pill becomes a baked gradient
        //     capsule and its square gradient overlay and mask go away.
        var gradientPill = Import("NerdyPillGradient", 100, new Vector4(64, 64, 64, 64));
        int baked = 0;
        foreach (var mask in scene.GetRootGameObjects().SelectMany(g => g.GetComponentsInChildren<Mask>(true)).ToList())
        {
            var image = mask.GetComponent<Image>(); var overlay = mask.transform.Find("Gradient");
            // Cards and the assistant bar masked their art and sheen to the card shape; both are pre-rounded now.
            if (image == null || overlay == null) { if (image != null) EditorUtility.SetDirty(image); UnityEngine.Object.DestroyImmediate(mask); continue; }
            UnityEngine.Object.DestroyImmediate(mask);
            overlay.gameObject.SetActive(false);
            var rect = image.rectTransform.rect;
            image.sprite = gradientPill; image.type = Image.Type.Sliced; image.color = Color.white;
            image.pixelsPerUnitMultiplier = 64f / (Mathf.Max(1f, Mathf.Min(rect.width, rect.height)) / 2f);
            EditorUtility.SetDirty(image); baked++;
        }
        report.Add(baked + " gradient pills baked");

        // 4. Cards: shared shape, hairline stroke, soft shadow behind (the assistant bar moves between canvases, so it
        //    gets the stroke only).
        var cards = new List<Image> { n.consentRoot.GetComponent<Image>(), n.welcomeRoot.GetComponent<Image>() };
        cards.AddRange(n.catalogRoot.GetComponentsInChildren<Button>(true).Where(b => b.name.StartsWith("Card ")).Select(b => b.GetComponent<Image>()));
        cards.AddRange(images.Where(i => i.name == "Backdrop"));
        foreach (var c in cards) { c.sprite = card; c.type = Image.Type.Sliced; c.pixelsPerUnitMultiplier = 1f; Stroke(c, stroke); Shadow(c, shadow); }
        var hud = n.hudRoot.GetComponent<Image>(); hud.sprite = card; hud.type = Image.Type.Sliced; hud.pixelsPerUnitMultiplier = 1f; Stroke(hud, stroke);
        var glass = n.hudRoot.transform.Find("Glass")?.GetComponent<Image>();
        if (glass != null) { glass.sprite = card; glass.type = Image.Type.Sliced; glass.pixelsPerUnitMultiplier = 1f; glass.color = new Color(1f, 1f, 1f, 0.04f); EditorUtility.SetDirty(glass); }
        report.Add(cards.Count + " cards with stroke and shadow; assistant bar stroked");

        // 5. Catalog art follows the card's rounded top corners and fades softly into the card body.
        foreach (var b in n.catalogRoot.GetComponentsInChildren<Button>(true).Where(b => b.name.StartsWith("Card ")))
        {
            var artImage = b.transform.Find("Art").GetComponent<Image>(); artImage.sprite = art; artImage.type = Image.Type.Simple; artImage.preserveAspect = false;
            var fadeImage = b.transform.Find("Fade").GetComponent<Image>(); fadeImage.sprite = fade; fadeImage.type = Image.Type.Simple;
            var body = b.GetComponent<Image>().color; fadeImage.color = new Color(body.r, body.g, body.b, 1f);
            // The fade's opaque bottom covers the art's lower edge, so no hard line shows where the art ends.
            var ar = artImage.rectTransform; var fr = fadeImage.rectTransform;
            fr.anchoredPosition = new Vector2(fr.anchoredPosition.x, ar.anchoredPosition.y - ar.sizeDelta.y / 2 + fr.sizeDelta.y / 2 - 3f);
            EditorUtility.SetDirty(artImage); EditorUtility.SetDirty(fadeImage);
        }

        // 6. Assistant caption stays inside the bar with a margin and shrinks when a line runs long.
        var caption = n.captionText.rectTransform; caption.anchoredPosition = new Vector2(caption.anchoredPosition.x, 12f); caption.sizeDelta = new Vector2(caption.sizeDelta.x, 64f);
        n.captionText.enableAutoSizing = true; n.captionText.fontSizeMax = Mathf.Max(18f, n.captionText.fontSize); n.captionText.fontSizeMin = 12f;
        n.captionText.verticalAlignment = VerticalAlignmentOptions.Middle; n.captionText.overflowMode = TextOverflowModes.Ellipsis;
        EditorUtility.SetDirty(n.captionText);

        EditorSceneManager.MarkSceneDirty(scene);
        if (!EditorSceneManager.SaveScene(scene)) throw new InvalidOperationException("Scene save failed.");
        AssetDatabase.SaveAssets();
        return "Cards polished: " + string.Join("; ", report) + ". Scene saved.";
    }

    static Sprite Import(string name, float pixelsPerUnit, Vector4 border)
    {
        string path = Sprites + name + ".png";
        var importer = (TextureImporter)AssetImporter.GetAtPath(path) ?? throw new InvalidOperationException("Sprite missing (run scripts/make_card_sprites.py): " + path);
        importer.textureType = TextureImporterType.Sprite; importer.spriteImportMode = SpriteImportMode.Single;
        importer.spritePixelsPerUnit = pixelsPerUnit; importer.spriteBorder = border;
        importer.mipmapEnabled = true; importer.filterMode = FilterMode.Trilinear; importer.wrapMode = TextureWrapMode.Clamp;
        importer.alphaIsTransparency = true; importer.textureCompression = TextureImporterCompression.Uncompressed; importer.sRGBTexture = true;
        var settings = new TextureImporterSettings(); importer.ReadTextureSettings(settings); settings.spriteMeshType = SpriteMeshType.FullRect; importer.SetTextureSettings(settings);
        importer.SaveAndReimport();
        return AssetDatabase.LoadAssetAtPath<Sprite>(path);
    }

    static void Stroke(Image card, Sprite sprite)
    {
        var existing = card.transform.Find("Stroke");
        var go = existing != null ? existing.gameObject : new GameObject("Stroke", typeof(RectTransform), typeof(Image));
        go.transform.SetParent(card.transform, false); go.transform.SetAsLastSibling();
        var r = go.GetComponent<RectTransform>(); r.anchorMin = Vector2.zero; r.anchorMax = Vector2.one; r.offsetMin = Vector2.zero; r.offsetMax = Vector2.zero; r.localScale = Vector3.one;
        var image = go.GetComponent<Image>(); image.sprite = sprite; image.type = Image.Type.Sliced; image.pixelsPerUnitMultiplier = 1f;
        image.color = new Color(1f, 1f, 1f, 0.14f); image.raycastTarget = false;
        EditorUtility.SetDirty(image);
    }

    static void Shadow(Image card, Sprite sprite)
    {
        var parent = card.transform.parent; string name = card.name + " shadow";
        var existing = parent.Find(name);
        var go = existing != null ? existing.gameObject : new GameObject(name, typeof(RectTransform), typeof(Image), typeof(LayoutElement));
        go.transform.SetParent(parent, false);
        var cr = card.rectTransform; var r = go.GetComponent<RectTransform>();
        r.anchorMin = cr.anchorMin; r.anchorMax = cr.anchorMax; r.pivot = cr.pivot; r.localRotation = cr.localRotation; r.localScale = cr.localScale;
        r.sizeDelta = cr.sizeDelta + new Vector2(ShadowPad * 2, ShadowPad * 2);
        r.anchoredPosition3D = new Vector3(cr.anchoredPosition.x, cr.anchoredPosition.y - ShadowDrop, cr.anchoredPosition3D.z);
        var image = go.GetComponent<Image>(); image.sprite = sprite; image.type = Image.Type.Sliced; image.pixelsPerUnitMultiplier = 1f;
        image.color = new Color(0f, 0f, 0f, 0.4f * card.color.a); image.raycastTarget = false;
        (go.GetComponent<LayoutElement>() ?? go.AddComponent<LayoutElement>()).ignoreLayout = true;
        go.SetActive(card.gameObject.activeSelf);
        var link = card.GetComponent<Airlift.Presentation.CardShadowLink>() ?? card.gameObject.AddComponent<Airlift.Presentation.CardShadowLink>();
        link.shadow = go; EditorUtility.SetDirty(link);
        if (go.transform.GetSiblingIndex() > card.transform.GetSiblingIndex()) go.transform.SetSiblingIndex(card.transform.GetSiblingIndex());   // just before the card
        EditorUtility.SetDirty(image);
    }
}
